AWSTemplateFormatVersion: "2010-09-09"
Description: "EFS for K8s"
Parameters:
  VpcCidr:
    Description: CIDR of Matsoo VPC
    Type: String
    Default: 10.0.0.0/16
  MatsooVPC:
    Description: VPC ID of Matsoo VPC
    Type: AWS::EC2::VPC::Id
  EksNodeSecurityGroup:
    Description: For EFS networking access permission
    Type: AWS::EC2::SecurityGroup::Id
  PrivSubnet1:
    Description: ID of private subnet 1 in Matsoo VPC
    Type: AWS::EC2::Subnet::Id
  PrivSubnet2:
    Description: ID of private subnet 2 in Matsoo VPC
    Type: AWS::EC2::Subnet::Id

Resources:
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties: 
      PerformanceMode: generalPurpose

  MountTargetPrivSubnet1:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref PrivSubnet1
      SecurityGroups: 
        - !Ref EksNodeSecurityGroup

  MountTargetPrivSubnet2:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref PrivSubnet2
      SecurityGroups: 
        - !Ref EksNodeSecurityGroup
 
Outputs:
  FileSystemId: 
    Description: ID of EFS
    Value: !Ref FileSystem
