AWSTemplateFormatVersion: "2010-09-09"
Description: "Matsoo EKS Authentication"
Parameters:
  SystemName:
    Description: An system name that is prefixed to resource names
    Type: String
    Default: matsoo-eks
Resources:
  EksClusterRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${SystemName}-cluster
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  EksFargateRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${SystemName}-fargate
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks-fargate-pods.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  EksWorkerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${SystemName}-worker
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  EfsCsiDriverPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: EKS_EFS_CSI_Driver_Policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'elasticfilesystem:DescribeFileSystems'
              - 'elasticfilesystem:DescribeAccessPoints'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'elasticfilesystem:CreateAccessPoint'
            Resource: '*'
            Condition:
              StringLike:
                aws:RequestTag/efs.csi.aws.com/cluster: "true"
          - Effect: Allow
            Action:
              - 'elasticfilesystem:DeleteAccessPoint'
            Resource: '*'
            Condition:
              StringEquals:
                aws:RequestTag/efs.csi.aws.com/cluster: "true"
      Roles:
        - !Ref EfsRole

  EfsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${SystemName}-efs
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'

