AWSTemplateFormatVersion: "2010-09-09"
Description: "Matsoo EKS"
Parameters:
  SystemName:
    Description: An system name that is prefixed to resource names
    Type: String
    Default: matsoo
  VpcCidrRange:
    Description: CIDR of this VPC
    Type: String
    Default: 1.0.0.0/16
  ClusterSecurityGroupList:
    Description: EKS cluster's security groups
    Type: List<AWS::EC2::SecurityGroup::Id>
  ClusterSubnetList:
    Description: EKS cluster's subnets 
    Type: List<AWS::EC2::Subnet::Id>
  ClusterIamRole:
    Description: EKS cluster's IAM role
    Type: String
  NodeIamRole:
    Description: EKS nodes' IAM role
    Type: String
  PrivateSubnetList:
    Description: EKS Node's private subnets 
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  EksCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: matsoo
      Version: '1.19'
      RoleArn: !Ref ClusterIamRole
      ResourcesVpcConfig:
        SecurityGroupIds: !Ref ClusterSecurityGroupList
        SubnetIds: !Ref ClusterSubnetList

  WorkerNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      NodegroupName: matsoo-workers
      ClusterName: !Ref EksCluster
      NodeRole: !Ref NodeIamRole
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 1
      Labels:
        kubernetes.io/cluster/matsoo: owned
      Subnets: !Ref PrivateSubnetList
