AWSTemplateFormatVersion: "2010-09-09"
Description: "Matsoo EKS"
Parameters:
  SystemName:
    Description: An system name that is prefixed to resource names
    Type: String
    Default: matsoo
  VpcCidrRange:
    Description: CIDR of this VPC
    Type: String
    Default: 10.0.0.0/16
  ClusterSecurityGroupList:
    Description: EKS cluster's security groups
    Type: List<AWS::EC2::SecurityGroup::Id>
  ClusterSubnetList:
    Description: EKS cluster's subnets 
    Type: List<AWS::EC2::Subnet::Id>
  ClusterIamRole:
    Description: EKS cluster's IAM role
    Type: String
  NodeIamRole:
    Description: EKS nodes' IAM role
    Type: String
  NodeGroupMinSize:
    Type: Number
    Description: Minimum size of Node Group.
    Default: 2
  NodeGroupDesiredSize:
    Type: Number
    Description: Desired size of Node Group.
    Default: 2
  NodeGroupMaxSize:
    Type: Number
    Description: Maximum size of Node Group.
    Default: 2

Resources:
  EksCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: matsoo
      Version: '1.19'
      RoleArn: !Ref ClusterIamRole
      ResourcesVpcConfig:
        SecurityGroupIds: !Ref ClusterSecurityGroupList
        SubnetIds: !Ref ClusterSubnetList

  WorkerNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      NodegroupName: matsoo-workers
      ClusterName: !Ref EksCluster
      NodeRole: !Ref NodeIamRole
      ScalingConfig:
        MinSize: !Ref NodeGroupMinSize
        DesiredSize: !Ref NodeGroupDesiredSize
        MaxSize: !Ref NodeGroupMaxSize
      Subnets: !Ref ClusterSubnetList
