AWSTemplateFormatVersion: "2010-09-09"
Description: "Matsoo Network"
Parameters:
  SystemName:
    Description: "A system name that is prefixed to resource names"
    Type: String
    Default: matsoo
  VpcCidrRange:
    Description: "CIDR of this VPC"
    Type: String
    Default: 1.0.0.0/16

  PubSubnet1CidrRange:
    Description: "CIDR of public subnet 1"
    Type: String
    Default: 1.0.0.0/24

  PubSubnet2CidrRange:
    Description: "CIDR of public subnet 2"
    Type: String
    Default: 1.0.10.0/24

  PrivSubnet1CidrRange:
    Description: "CIDR of private subnet 1"
    Type: String
    Default: 1.0.20.0/24

  PrivSubnet2CidrRange:
    Description: "CIDR of private subnet 2"
    Type: String
    Default: 1.0.30.0/24

Resources:
  MatsooVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrRange
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-vpc

  InternetGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-igw

  InternetGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGW
      VpcId: !Ref MatsooVPC

  AtlWavelength:
    Type: AWS::EC2::CarrierGateway
    Properties: 
      VpcId: !Ref MatsooVPC
      Tags:
        - Key: Name
          Value: atl-wl

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MatsooVPC
      AvailabilityZone: !Select 
        - 0
        - !GetAZs ""
      CidrBlock: !Ref PubSubnet1CidrRange
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-pub-sn-1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MatsooVPC
      AvailabilityZone: !Select 
        - 2
        - !GetAZs ""
      CidrBlock: !Ref PubSubnet2CidrRange
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-pub-sn-2

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MatsooVPC
      AvailabilityZone: !Select 
        - 0
        - !GetAZs ""
      CidrBlock: !Ref PrivSubnet1CidrRange
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-priv-sn-1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MatsooVPC
      AvailabilityZone: !Select 
        - 2
        - !GetAZs ""
      CidrBlock: !Ref PrivSubnet2CidrRange
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-priv-sn-2

  WavelengthPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MatsooVPC
      AvailabilityZone: us-east-1-wl1-bos-wlz-1
      CidrBlock: 1.0.250.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          #Value: atl-wl
          Value: !Sub ${SystemName}-priv-sn-wl

  NatGatewayEIP1:
    Type: AWS::EC2::EIP
    DependsOn: InternetGWAttachment
    Properties:
      Domain: vpc

  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP1.AllocationId
      SubnetId: !Ref PublicSubnet1

  NatGatewayEIP2:
    Type: AWS::EC2::EIP
    DependsOn: InternetGWAttachment
    Properties:
      Domain: vpc

  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP2.AllocationId
      SubnetId: !Ref PublicSubnet2

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MatsooVPC
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-pub-route

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGWAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGW

  PublicSubnetRTAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PublicSubnetRTAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MatsooVPC
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-priv-route-1

  DefaultPrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway1

  PrivateSubnetRTAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId: !Ref PrivateSubnet1

  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MatsooVPC
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-priv-route-2

  DefaultPrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway2

  PrivateSubnetRTAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      SubnetId: !Ref PrivateSubnet2

  WavelengthRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MatsooVPC
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-priv-route-wl

  DefaultWavelengthRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref WavelengthRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      CarrierGatewayId: !Ref AtlWavelength

  WavelengthSubnetRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref WavelengthRouteTable
      SubnetId: !Ref WavelengthPrivateSubnet

  EksClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "eks-cluster-sg"
      GroupDescription: "Security group for EKS control plane (cluster)"
      VpcId: !Ref MatsooVPC
